### ISSUE TITLE
Pictorial Examples

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/kimimaro#29]
![01](https://user-images.githubusercontent.com/2517065/62669795-02b5a080-b95f-11e9-9196-61901f08c28a.jpeg)
![02](https://user-images.githubusercontent.com/2517065/62669796-02b5a080-b95f-11e9-9906-99c5bd3702ce.jpeg)
![03](https://user-images.githubusercontent.com/2517065/62669797-02b5a080-b95f-11e9-98a0-188e20a2bf10.jpeg)
![04a](https://user-images.githubusercontent.com/2517065/62669798-02b5a080-b95f-11e9-8a5e-eac27489a4fb.jpeg)
![04b](https://user-images.githubusercontent.com/2517065/62669799-02b5a080-b95f-11e9-8580-2cdb95aef0b9.jpeg)
![04c](https://user-images.githubusercontent.com/2517065/62669800-02b5a080-b95f-11e9-882d-45fca22d48bc.jpeg)
![04d](https://user-images.githubusercontent.com/2517065/62669801-02b5a080-b95f-11e9-8188-a22720e9b98c.jpeg)
![05](https://user-images.githubusercontent.com/2517065/62669802-02b5a080-b95f-11e9-8bd5-30b9636ff658.jpeg)
![06](https://user-images.githubusercontent.com/2517065/62669804-034e3700-b95f-11e9-9ce0-6ac6b0d675b6.jpeg)
![07](https://user-images.githubusercontent.com/2517065/62669806-034e3700-b95f-11e9-9e5d-717fe82970b8.jpeg)
![scale_zero](https://user-images.githubusercontent.com/2517065/62669807-034e3700-b95f-11e9-9d1d-7b28822a2425.jpeg)
![const_zero](https://user-images.githubusercontent.com/2517065/62669808-034e3700-b95f-11e9-8b6a-dd3f94f578e9.jpeg)

**Comment by nkemnitz** [comment]
Those are awesome!

**Comment by william-silversmith** [comment]
Thanks! I'm using them here: https://github.com/seung-lab/kimimaro/wiki/A-Pictorial-Guide-to-TEASAR-Skeletonization

**Comment by william-silversmith** [comment]
<img width="510" alt="Screen Shot 2019-08-07 at 10 39 12 PM" src="https://user-images.githubusercontent.com/2517065/62671288-43fc7f00-b964-11e9-97fa-cff393a1f3d8.png">
distance transform of a square
