### ISSUE TITLE
Skeleton has local hallow for stochiastic structure 

### ISSUE THREAD

**Issue by HaominIsMe** [seung-lab/kimimaro#30]
Hello kimimaro users,

I am very new to kimimaro. I am trying to use the `kimimaro.skeletonize()` to skeletonize my stochastic structure. I didn't specify any of the`teasar_params` and it returns the skeleton with hollow inside, as the screenshot showed. I tried to tune `scale` and `const`, but it still not solve the issue. Could I have some suggestions from you?
![Screen Shot 2019-08-13 at 5 20 19 PM](https://user-images.githubusercontent.com/44219935/62978198-b222c500-bdee-11e9-9669-25d1d761f1dd.png)
[](url)

**Comment by william-silversmith** [comment]
Hi HaominIsMe!

I think this is a bit difficult to answer without seeing a representation of the space you are trying to skeletonize. Can you post what scale and const values you tried? Is your data isotropic (meaning all axes have the same dimension)? 

Thanks!
Will

**Comment by william-silversmith** [comment]
Also, if you haven't seen them, check out these tutorials that might help you understand what's going on:

https://github.com/seung-lab/kimimaro/wiki/Intuition-for-Setting-Parameters-const-and-scale
https://github.com/seung-lab/kimimaro/wiki/A-Pictorial-Guide-to-TEASAR-Skeletonization

**Comment by HaominIsMe** [comment]
The space is generated with small shape(64, 64, 64), and I would like to skeleton the voxels with label 1. I check the tutorials explaining scale and const, which I set `scale=10, const=0` based on my understanding. 
Here is how I did:
```
import kimimaro
labels = np.load('structure.npy')
labels = labels.astype(int)
skels = kimimaro.skeletonize(
  labels, 
  teasar_params={
    'scale': 10,
    'const': 0, # physical units
    }
)
```
Please unzip the attachment for the structure file.
[structure.npy.zip](https://github.com/seung-lab/kimimaro/files/3499083/structure.npy.zip)

**Comment by william-silversmith** [comment]
Thanks for the data, that's very helpful!

I ran the following code and got this output:

```python
import numpy as np 
from cloudvolume import * 
import kimimaro

img = np.load('structure.npy')
img = img.astype(np.uint8)

skels = kimimaro.skeletonize(
  img, 
  teasar_params={
    'scale': 1.5,
    'const': 3,
  },
  anisotropy=(1,1,1),
  fix_branching=True,
  fix_borders=True,
)

skels[1].viewer()
```
Is this more what you're looking for?

![image](https://user-images.githubusercontent.com/2517065/62981618-b69fab80-bdf7-11e9-8606-49a57a8e3533.png)

**Comment by william-silversmith** [comment]
You can also visualize your data a bit better like this:

```python
from cloudvolume import view
import numpy as np

img = img.astype(np.bool)
view(img)
```

**Comment by HaominIsMe** [comment]
Hi @william-silversmith 

Yes. This is exactly what I am looking for. Thanks for your help.

**Comment by william-silversmith** [comment]
Awesome! Glad I could help.
