### ISSUE TITLE
Avocado Protection (🥑)

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/kimimaro#40]
_Avocado (n.) 1. a delicious buttery fruit 2. a neuron cell body with its nucleus punched out._

Alyssa and I developed an anti-avocado attack plan last night. Here are some of the features:

Given you know there's a soma and you want to know if you are dealing with an avocado, you can march along a number of rays projected from the soma center. If the first different voxel encountered by each ray matches the other rays, you're in an avocado. If they are all different, you're in a non-avocado cell.

Some of the avocado fruits have holes in them, so a simple flood fill is insufficient. Therefore you need to do something more like:
```
labels = binary_fill_holes(labels)
while not labels[center]:
     labels = morophological_close(labels)
     labels = binary_fill_holes(labels)
```
For dealing with soma contacting the edge of the volume, once you know you're dealing with an avocado, paint a 1 voxel thick border on the faces touching the edge of the image. Then run binary fill holes.

**Comment by william-silversmith** [comment]
![image](https://user-images.githubusercontent.com/2517065/74965064-85291d80-53e2-11ea-8955-f0b9b1336fdb.png)

**Comment by shangmu** [comment]
Oh man. The poor avocado had its nucleus punched out and you guys are still conspiring to attack it? >_<

**Comment by william-silversmith** [comment]
We fight dirty.

**Comment by william-silversmith** [comment]
A 3D view.
![image](https://user-images.githubusercontent.com/2517065/75209830-51852500-574d-11ea-8c4f-4fc0504629e9.png)

**Comment by william-silversmith** [comment]
Fixing the hole in the avocado fruit is probably unnecessary. We can just do `binary_image = fruit + pit`

**Comment by william-silversmith** [comment]
Added in #43
