### ISSUE TITLE
support python3.8?

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/kimimaro#51]
I have accidentally add python3.8 in master directly (was indented to create a PR). 
https://github.com/seung-lab/kimimaro/commit/e287605a2869269d3ac834ea036238de37ec2bd1

Python 3.8 is the latest release, so we should support it? My chunkflow is using python3.8, it seems that there is an error in python3.8 build due to kimimaro. The build was good a few days ago, so the problem should come from a recent change of kimimaro.

https://travis-ci.org/github/seung-lab/chunkflow/builds/700591119

**Comment by jingpengw** [comment]
the build failed for python3.8
https://travis-ci.org/github/seung-lab/kimimaro/jobs/701101312

**Comment by cnzqy1** [comment]
I don't think the build is failing due to Python 3.8. I was installing Igneous and pip collected kimimaro 1.6.0 which failed to build, and had to specify `kimimaro==1.5.0` in `requirements.txt` to get around this issue.

**Comment by william-silversmith** [comment]
Looks like the python3.8 needed an updated cython to generate good code. I'll make a PR with working code and make a new release. Thanks for letting me know!
