### ISSUE TITLE
Kimimaro Should Accept Fortran and C Arrays

### ISSUE THREAD

**Issue by JueYean** [seung-lab/kimimaro#6]
I have tried to feed the package with a 3D Numpy array, which stores part of neuron signals. The Numpy array is a 300*300*300 binary map in which neuron is represented as 3 pixels wide cylinder.
     I am trying to get the skeleton of these neurons, but it seems not work to me. The package either returns Null or keeps runing without any results.
     I can show you the data if it is needed, looking for your reply.

**Comment by william-silversmith** [comment]
Hi JueYean! 

I suspect that the issue is that this package was designed for use with arrays in Fortran order. Would you be able to try applying `np.asfortranarray` to your data and see if it works then? If not, I'd love to see the code you used to generate the example data and I'll give it a try.

If that's the problem, I'll add a fix to Kimimaro to make sure it works in both array orientations.

Will

**Comment by JueYean** [comment]
Thanks for your reply, I will try as what you say.

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=blankxu&uid=blankxu%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22blankxu%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
blankxu

blankxu@outlook.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
On 3/18/2019 23:47，William Silversmith<notifications@github.com><mailto:notifications@github.com> wrote：

Hi JueYean!

I suspect that the issue is that this package was designed for use with arrays in Fortran order. Would you be able to try applying np.asfortranarray to your data and see if it works then? If not, I'd love to see the code you used to generate the example data and I'll give it a try.

If that's the problem, I'll add a fix to Kimimaro to make sure it works in both array orientations.

Will

**Comment by JueYean** [comment]
It works now, thank you a lot

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=blankxu&uid=blankxu%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22blankxu%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
blankxu

blankxu@outlook.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
On 3/18/2019 23:48，blankxu<blankxu@outlook.com><mailto:blankxu@outlook.com> wrote：
Thanks for your reply, I will try as what you say.

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=blankxu&uid=blankxu%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22blankxu%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
blankxu

blankxu@outlook.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
On 3/18/2019 23:47，William Silversmith<notifications@github.com><mailto:notifications@github.com> wrote：

Hi JueYean!

I suspect that the issue is that this package was designed for use with arrays in Fortran order. Would you be able to try applying np.asfortranarray to your data and see if it works then? If not, I'd love to see the code you used to generate the example data and I'll give it a try.

If that's the problem, I'll add a fix to Kimimaro to make sure it works in both array orientations.

Will

**Comment by william-silversmith** [comment]
Kimimaro 0.2.2 includes this fix by default now.

**Comment by dipaco** [comment]
Hi guys,

First, great library, thanks. I am using kimimaro==0.7.0 for an academic project, and @JueYean problem was happeining to me too. I was able to to use np.asfortranarray as suggested, and it solved the problem. But then @william-silversmith says that the bug is included in the 0.2.2 version. Did I get the wrong code? I used pip to install it.

Thanks.
