### ISSUE TITLE
Issue with pip installation.

### ISSUE THREAD

**Issue by JBum21** [seung-lab/kimimaro#60]
Hi there, 
Let me apologize in advance for my technical ineptitude. Hopefully this is a simple problem that you can help me figure out. 

When I run "pip install kimimaro" in my terminal, I received a long error code that seems to be related to the installation of psutil.

"Pip show psutil" returns the following, indicating it's been installed successfully:
      Name: psutil
      Version: 5.8.0
      Summary: Cross-platform lib for process and system monitoring in Python.
      Home-page: https://github.com/giampaolo/psutil
      Author: Giampaolo Rodola
      Author-email: g.rodola@gmail.com
      License: BSD
      Location: /Users/jacobbumgarner/opt/anaconda3/envs/micromap/lib/python3.7/site-packages
      Requires: 
      Required-by: spyder
      Note: you may need to restart the kernel to use updated packages.

The error code I get when running "Pip install kimimaro" can be found below with personal info retracted:

ERROR: Command errored out with exit status 1: /Users/**deleted**/opt/anaconda3/envs/micromap/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tx/**deleted**/T/pip-install-cwj2yufr/psutil_c0c9aad5fafe4d3eaeb57cc2ad6ab148/setup.py'"'"'; __file__='"'"'/private/var/folders/tx/**deleted**/T/pip-install-cwj2yufr/psutil_c0c9aad5fafe4d3eaeb57cc2ad6ab148/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tx/**deleted**/T/pip-record-4tjv3kke/install-record.txt --single-version-externally-managed --compile --install-headers /Users/**deleted**/opt/anaconda3/envs/micromap/include/python3.7m/psutil Check the logs for full command output

I deleted some long numeric strings from the error, as I'm not sure what they represent and am unsure whether they should be published. If you need these for any reason, please let me know.

Thanks for your help,
Jacob

**Comment by william-silversmith** [comment]
Hi Jacob,

This is pretty strange. psutil usually installs seamlessly. I can see you're using python37, but I'm not sure what OS this is (MacOS?). The error message you provided unfortunately doesn't contain enough information for me to understand what's going on. If you'd like a slightly more private way to send the full (anonymized) stack trace, you can email me at ws9 at princeton (deobfuscated of course).

**Comment by JBum21** [comment]
Thanks to William, I learned that I simply needed to run:
pip install cloud-files -U 

Not sure why this didn't install properly to begin with. Issue resolved
