### ISSUE TITLE
Obtain Skeleton Result as Numpy Array

### ISSUE THREAD

**Issue by chxii** [seung-lab/kimimaro#62]
Hello, 

I was trying to use this package, and Cloud Volume. Since I'm not familiar with Cloud Volume, I was wondering if it's possible to obtain the skeleton result as a numpy binary array (points on skeleton as 1, background as 0), or get the coordinates and radius of the skeleton. Thanks!

**Comment by william-silversmith** [comment]
Hi! You can find some information about how to use the skeleton object here: https://github.com/seung-lab/cloud-volume/wiki/Advanced-Topic:-Skeletons

To answer your question, the coordinates can be gotten as: `skel.vertices` and the radii as `skel.radii`.

**Comment by chxii** [comment]
Thanks for your quick reply. 
I have learned a lot from your packages. Thank you!!

![WechatIMG117](https://user-images.githubusercontent.com/16949423/120416178-504e9900-c38f-11eb-91c6-506c49424b2f.jpeg)

**Comment by william-silversmith** [comment]
Glad you found it useful Xi! Love the pic! 😍
