### ISSUE TITLE
Unbranched centerline between suggested points

### ISSUE THREAD

**Issue by urakubo** [seung-lab/kimimaro#69]
Hello, I am very impressed by the rapid and concise skeletonization of kimimaro, and I am grateful to use it for my study. In some case, I want to obtain an unbranched centerline along with a spiny dendrite (dendritic_segment.png). So I suggest the “extra_targets_before,” (red points) and set the 'max_paths' as 2. However, it does not work, and it returns blank skeletonization. If I increase the 'max_paths' to 3 or more, I can get a skeleton but with unnecessary branches, as shown in the attached two images (dendritic_segment.png, ellipsoid.png) .

I would very appreciate it if you could suggest a good way to obtain a single centerline only between suggested points. The behavior may be parameter-dependent, so I attach a sample program to replicate it (centerline.py).

![dendritic_segment](https://user-images.githubusercontent.com/32314975/145554107-ee7a5738-ffa9-4661-841c-3be747caaf15.png)

![ellipsoid](https://user-images.githubusercontent.com/32314975/145554179-18f1ec4d-951c-485b-9d25-6b32bc96bca5.png)

[centerline.py.txt](https://github.com/seung-lab/kimimaro/files/7691788/centerline.py.txt)

**Comment by william-silversmith** [comment]
Thanks for writing in Urakubo (and for being so polite as to include an easy example to work with)! This mode of operating is currently not supported, but it is a pretty easy feature to add. Let me get back to you after I've had a little bit to play around with it.

In the mean time, if you are in a hurry you can use the https://github.com/seung-lab/dijkstra3d library that Kimimaro uses directly. The "centerline" property will be lost though unless you do the extra processing Kimimaro does.

**Comment by william-silversmith** [comment]
@urakubo I created a PR with the functionality I think you want. It's much simpler than the skeletonize function and accepts only binary images and two points. I'm trying to decide if that's too limited. Should the function be more flexible?

```python
skel = kimimaro.connect_points(
  ellipse * id, 
  start, end,
  anisotropy=pitch,
)
```

<img width="496" alt="image" src="https://user-images.githubusercontent.com/2517065/145652387-7712f565-3dae-4380-8060-bae1f6007dc8.png">

**Comment by urakubo** [comment]
Thank you very much for your rapid implementation of a new function! I found the successful work. Probably, I will soon want to control the degree of ignorance of fine structure such as spines (e.g., to define/obtain a segment length). The parameters pdrf_scale and pdrf_exponent can be specified in connect_points. Aren’t the remaining scale and const required in this case? I am now comparing “compute_paths” and “point_to_point”..

**Comment by william-silversmith** [comment]
Glad it's working for you! For `connect_points` it only draws the centerline between two preselected points. The original function automatically determines the root node and draws a tree. scale and const are used to invalidate regions of the structure so that the next target point can be selected.

The pdrf parameters control the intensity of the centering field. Dijkstra's algorithm draws the path between the points within this field.

**Comment by urakubo** [comment]
Thank you for your help! I learnt that the scale and const are used to determine a root node and branch-end points. Anyway, I confirmed that “connect _points” completely works on my setup, as the attached image!

![spiny_dendrite](https://user-images.githubusercontent.com/32314975/145708652-ab6709a6-1f57-47c0-8574-50a6f0457d13.png)

**Comment by william-silversmith** [comment]
Fantastic! In that case, I'll make a release with the new function. In the future, I might update it to include functions like "link this chain of points together" or "draw from this root to these points". Glad I was able to help your research!
