### ISSUE TITLE
How to output the binary 3D skeleton?

### ISSUE THREAD

**Issue by HHHit** [seung-lab/kimimaro#71]
I was hoping to obtain the binary skeleton from a relatively sparse labeled volume. I understand the current output is in the format of cloud volume skeleton but is there a way to obtain the 3D skeleton (same size as the input volume)?

**Comment by william-silversmith** [comment]
Hi HHHit, this is really easy to accomplish. With the skeleton as `skel` and original image `labels` with numpy array `anisotropy`:

```
import numpy as np

binimg = np.zeros(labels.shape, dtype=np.bool)
verts = skel.vertices // anisotropy
binimg[verts] = True # if this fancy indexing doesn't work you can loop over skel.vertices and assign each point
```

**Comment by HHHit** [comment]
Thanks! That really helps!
