### ISSUE TITLE
Can't install kimimaro (Windows 64-bit, Python 3.10)

### ISSUE THREAD

**Issue by ChristianNikolov** [seung-lab/kimimaro#73]
Hello,

thank you for creating kimimaro and making it public, my Doctor's Thesis would greatly benefit from it. I have just one problem, I can't install it (Python 3.10.5, Windows 11). I made a post seeking for help, where the error I get is displayed: https://stackoverflow.com/questions/72867820/error-while-installing-kimimaro-3-2-1-for-python

I am sorry for bothering this thread with an installation problem but I don't know how to resolve the issue otherwise.

**Comment by william-silversmith** [comment]
Hi Christian,

Your issue is very strange. When you run "import DracoPy" does that work for you? What environment are you installing it into? Is it a virutalenv, conda, or other? If you're not using a virtual environment, using one might fix it for you.

**Comment by ChristianNikolov** [comment]
Update, I created a new **virtual environment** and tried installing **kimimaro** there, unfortunately the same error :/ The interesting thing is I can install **DracoPy** successfully on its own as a Python Package. However when the kimimaro installation process tries to create a wheel for DracoPy (with or without DracoPy installed), it fails.
 
It says that **CMake** can't find **ninja** (although I have installed ninja as a Python Package, I see ninja.exe in the Scripts Folder of the virtual environment, `ninja --version` in cmd works and from the error message it's clear that CMake searches for ninja.exe in the correct folder, i.e Scripts folder of the virtual environment). There also seems to be a problem with Cmake's source and build directories.

**Comment by william-silversmith** [comment]
The thing that is weird is that Kimimaro should not be trying to install DracoPy from source, it should be finding and downloading the binary. If you install DracoPy first successfully, Kimimaro should be satisfied and not try to build it again. DracoPy is kind of annoying to build from source, so I'm not surprised you're having issues doing it that way. If we can figure out why it's not picking a wheel or finding the existing installation, that would help a lot.

**Comment by ChristianNikolov** [comment]
Oh, I see. Now I noticed, before trying to build the wheel for DracoPy, Kimimaro says: 
```
Collecting DracoPy~=1.0.0
  Using cached DracoPy-1.0.1.tar.gz (29.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
```
And the DracoPy I have installed is Version 1.1.1. 
I am going to try installing DracoPy 1.0.0, maybe Kimimaro doesn't recognise the higher version.

**Comment by ChristianNikolov** [comment]
thanks!! I'll try with py3.9
