### ISSUE TITLE
Skeleton as Binary 3D Numpy Array

### ISSUE THREAD

**Issue by ChristianNikolov** [seung-lab/kimimaro#74]
Hello William,

thank you very much for the help so far, I am sorry for troubling you again. 
I am trying to get the output of Kimimaro in form of a Numpy Array. I read the issues thread and found 2 of your answers on the topic, however I can't make it work in my case.
 
Here is the code I am trying (1. I import a Binary 8-bit 3D .tif Segmentation (Background voxels have a value of 0, Structure voxels have a value of 255) as **im_t** with a shape (54, 212, 48) -> that's my input, I checked it via print(im_t); 2. I run Kimimaro with **skel** as output; 3. I try to get the vertices of the skeleton as you suggest): 

```
import numpy as np
import kimimaro
import os
import tifffile

paths = ["C:/Users/Christian Nikolov/Desktop/SlicerTest/Temp7/bina.tif" for path in os.listdir("C:/Users/Christian Nikolov/Desktop/SlicerTest/Temp7")]
for path in paths:
    im_t = tifffile.imread(path)

#attempts to alter the input and make it work:
#im_t = np.asfortranarray(im_t)
#im_t = np.array(im_t)
#im_t = np.array(im_t, bool)

skel = kimimaro.skeletonize(im_t)

binimg = np.zeros(im_t.shape, dtype=bool)
verts = skel.vertices
binimg[verts] = True

print(binimg)
```

When I run this code I get the following output: 

```
Skeletonizing Labels: 100%|██████████| 1/1 [00:00<00:00, 83.07it/s]
Traceback (most recent call last):
  File "C:\Users\Christian Nikolov\Desktop\PythonProjects\Kimimaro3.9a\main.py", line 17, in <module>
    verts = skel.vertices
AttributeError: 'dict' object has no attribute 'vertices'

Process finished with exit code 1
```

I tried altering my input (see # at the input code) by uncommenting the lines one at a time, but it didn't help, the output stays the same. As you may notice, I also left the \\\ anisotropy from your code away because I wasn't sure how to make it work (it should be a numpy.array I define?). Last question, if we get the coordinates of the vertices, we would still need to connect those points in order to obtain the skeleton?

**Comment by william-silversmith** [comment]
Hi Christian,

I'm glad you asked! There are a few elements of the code above that don't make much sense to me. For example, the paths variable will contain the same path over and over again. Did you mean something more like this?

```python
import numpy as np
import kimimaro
import os
import tifffile

paths = os.listdir("C:/Users/Christian Nikolov/Desktop/SlicerTest/Temp7")
imgs = [ tifffile.imread(path) for path in paths ] 
shape = imgs[0].shape
im_t = np.zeros([ shape[0], shape[1], len(imgs) ], dtype=np.uint8)
for z, im in enumerate(imgs):
    im_t[:,:,z] = im

skel = kimimaro.skeletonize(im_t)
skel = skel[list(skel.keys())[0]] 

binimg = np.zeros(im_t.shape, dtype=bool)
verts = skel.vertices
binimg[verts] = True
```
> Last question, if we get the coordinates of the vertices, we would still need to connect those points in order to obtain the skeleton?

The skeleton is at a resolution of 1 voxel, so it is not necessary to consider the edges while painting a binary image. However, the skeleton also has `skel.edges` which contains the edge list. `skel.radii` has the distance to boundary of each vertex.

Will

**Comment by ChristianNikolov** [comment]
Hi William,

thank you very much! 

Sorry for the confusion with the path, I got it from another code I use. The idea of the path is just to import a segmentation.tif as a 3d numpy array. I simplified it as follows and it still works:
 
```
path = ["C:/Users/Christian Nikolov/Desktop/SlicerTest/Temp7/bina.tif"]
img = tifffile.imread(path)
 
#img is then a 3d numpy array with a value of 0 at background voxels and 255 at structure voxels 
```

With the line of code you added to the vertices extraction method (`skel = skel[list(skel.keys())[0]]`) it now works!! 
I ran it and printed the `verts` variable. It is now an array with multiple rowes and 3 columns, i.e values per row. I guess it is exactly the coordinates of each vertex in 3d space, each vertex getting its separate row. 

And lastly, I thought that the vertices are the edges. But from your answer I see that the vertices are the points composing the skeleton? So each vertex is a voxel of the skeleton?

Thank you again, I am now going to try finalising the code and will give feedback how it went.

**Comment by william-silversmith** [comment]
Yes, each vertex is localized to a unique voxel. The vertices are strongly
26-connected within a given label connected component and so there are no
breaks in the chain.

You can extract individual connected components from the skeleton using
skel.components() which uses edge information to determine which voxels are
connected.

**Comment by ChristianNikolov** [comment]
Update: it works great now. 
It helps a ton to be able to adjust the skeletonisation settings. For my purposes I seem to get the best results with scale= 1 and const= 5 or scale= 2 and const = 0. In this way definitely get an improvement compared to 3D Skeletonize of ImageJ because it leaves only the center line of the Structure, with Kimimaro I can keep some of the smaller scale lateral complexity of the Structure

**Comment by william-silversmith** [comment]
Fantastic, I'm glad it was helpful!!

**Comment by ChristianNikolov** [comment]
And sorry Will, I have one last question because it is important for my work: **what is the unit of the `const` parameter**? The wiki says: "...the units of D(x,y,z) and const are physical units (e.g. nanometers)...". To be more exact, the physical unit should be Voxel? Because Kimimaro measures distance in number of Voxels, without converting it to e.g mm or nanometers?

**Comment by william-silversmith** [comment]
Hi Christian,

The const units are physical units, meaning the same unit you use for
anisotropy. The invalidation distance is a physical radius because it would
mean wildly different things in anisotropic datasets if it were specified
in voxels.

Will

**Comment by ChristianNikolov** [comment]
Thanks Will! 
I also read in the paper you have cited about TAESAR, which says: "In order to apply the Dijkstra algorithm as a sub-step of our skeleton algorithm, the volume data has to be transformed into a graph. We implicitly map the voxels to graph vertices, and the voxel neighbor relations to graph edges...**As weights, we use the exact Euclidian distances between the voxels that correspond to the graph vertices at both ends of the edge**. However, even when including corrections for anisotropic volumes...". And also "It is most accurate to use a ... Euclidian metric for isotropic volumes and a metric with axis specific corrections for anisotropic volumes.".

So I guess the answer to my question is that the volume data (voxel grid) is being transformed to a graph. If the voxels are anisotropic the graph is being corrected. However the weight of the metric remains the Euclidian distance between voxels or graph vertices at both ends of an edge. -> there is no transformation in mm, mikrom or nanom

**Comment by william-silversmith** [comment]
That's right except my library dijkstra3d uses an implicit graph
representation on the 3d image grid. There's no explicit graph represented
;)

Yes "physical" distances between voxels are what counts. The anisotropy of
the voxels is usually given in a unit like nm so whatever unit the
anisotropy is, that's the distance unit.

**Comment by ChristianNikolov** [comment]
oh I see, so what I say would be true if you have isotropic voxels and leave the anisotropy = (1, 1, 1), which is the case for me. Otherwise it would multiply the voxel distances with what you input as anisotropy, practically transforming the distance in the unit metric you type in thank you!

**Comment by william-silversmith** [comment]
Bingo 😊 The data kimimaro was designed for is serial section electron
microscopy where xy dimensions are 4nm x 4 nm and z slices cut by a diamond
knife at 40 nm. Ofc, isotropic data is also supported by leaving the
defaults in place as you noted.
