### ISSUE TITLE
Verbose flag

### ISSUE THREAD

**Issue by 0xJustin** [seung-lab/kimimaro#77]
Hi - I am somewhat of a power user of both this and meshparty skeletonize. Is there any chance you could add a verbose flag to control whether or not the for loop here uses tqdm: https://github.com/seung-lab/kimimaro/blob/master/kimimaro/intake.py#L377 
Thanks :)

**Comment by william-silversmith** [comment]
Hi Justin,

Thanks for writing in! Which interface are you using, Python or CLI? It seems the tqdm instance is already instrumented with a progress flag. Do you mean you want to disable that progress bar specifically?

I tried running `kimimaro forge --progress -p 4 connectomics.npy --no-fill-holes` and there seemed to be only one progress bar. To disable progress, just don't add `--progress`. In the python interface, you can set:

```python
kimimaro.skeletonize(..., progress=False)
```

Thanks!
Will

**Comment by william-silversmith** [comment]
By the way, in case you weren't aware, I believe there are a set of mesh to skeleton algorithms including the meshparty algorithm included in https://github.com/navis-org/skeletor though I haven't used it.

**Comment by 0xJustin** [comment]
Wow I'm a complete goofball I can't believe I missed that flag! Thanks for your nice response- also thanks for that link! I've been doing quite a bit of mesh skeletonization as part of a pipeline for finding EM error locations using the mesh, and the skeletonization part of the approach is certainly the computational bottleneck. I'm keen to see if any of the other algorithms have potential for speedup
