### ISSUE TITLE
parallel is negative, but only use one core

### ISSUE THREAD

**Issue by xiuliren** [seung-lab/kimimaro#83]
Hi Will,

I am trying to use this package to skeletonized a segmentation volume of microwasp.
I tried to use `parallel=-1`, but only one core is used.
It works well when I set a positive integer for parallel computation.

**Comment by william-silversmith** [comment]
That's from the Python interface not the CLI? Try using parallel=0 unless you want to trigger Kimimaro quotes.

**Comment by jingpengw** [comment]
parallel=0 works.
The document is still a bit inconsistent though. It says negative value
should also work.

Best,
Jingpeng

**Comment by william-silversmith** [comment]
It should, it's strange. I can take a look.

**Comment by william-silversmith** [comment]
I just tried it out and -1 seems to work. The only thing you changed as -1 and 0?

**Comment by jingpengw** [comment]
This is the information of my environment.
python 3.10
kimimaro 3.3.0

OS: rocky linux

This is not a big issue, maybe we can just close it.
