### ISSUE TITLE
Compatibility issue with Igneous' Skeletonization

### ISSUE THREAD

**Issue by SanjeevRJ** [seung-lab/kimimaro#88]
Hi,

I'm trying to use Igneous' skeletonization feature and I believe commit #87 is causing some compatibility issues between the two packages. There are some non-TEASAR related parameters that I think you can't set on the Igneous side such as anisotropy, which results in the following error `TypeError: roll_invalidation_ball_inside_component() takes at least 6 positional arguments (3 given)`  when running Igneous' skeletonization. Are there any workarounds for this issue? Thanks!

**Comment by william-silversmith** [comment]
Oh hi Sanjeev! This is a problem that should have been fixed in the latest release. Try updating Kimimaro and see if that fixes it for you.
