### ISSUE TITLE
Increasing resolution of the vertex positions to sub-voxel level

### ISSUE THREAD

**Issue by RomStriker** [seung-lab/kimimaro#91]
Hi, 

Thanks for the great work. I am using Kimimaro to get the centerline of Lung airway trees from the ATM'22 dataset. Is there a way to increase the resolution of the positions of each vertex from the voxel level to the sub-voxel level like 0.1 voxel? For example, I have extracted the centerline trees, using Kimimaro and Slicer3D's VMTK centerline extraction toolkit, in the image the green graph is from Kimimaro and the purple is from VMTK.
![image](https://github.com/user-attachments/assets/c7bc07b2-abbb-404c-b321-8b2d54d2fdfd)
As you can see the VMTK is much smoother due to the higher resolution vertex positions, while the Kimimaro output seems to jump around. I want to use Kimimaro as it is much faster, robust, and manages to capture more branches, but it would be great if it could also produce positions with higher resolution. I tried to increase the resolution using the argument 'anisotropy=(16,16,16)' such that each voxel has a spatial resolution of 16, but it resulted in the original positions times 16. Any help would be appreciated.

**Comment by william-silversmith** [comment]
Hi! I'm not sure there are fantastic options for getting the same result using Kimimaro, they are different algorithms. The vibrations come from finding the shortest path across a penalty field which includes all 26 possible directions of motion.

A possible remedy would be to apply a smoothing filter to the Kimimaro output. I wrote a moving average smoothing filter and uploaded it to the master branch of CloudVolume's Skeleton class (that Kimimaro outputs): 

https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/skeleton.py#L929-L963

Give that a try and see if that does what you need. The main downside is that this simple operation can't guarantee that points will remain inside the object (though it could make use of radius information to do so actually... I'll have to think about this).

**Comment by william-silversmith** [comment]
Here's some before and after pics using n=5 vertices and n=15 vertices

original
<img width="1075" alt="image" src="https://github.com/user-attachments/assets/bd221c33-6b5c-483e-b132-c2b035373b3d">

n=3
<img width="1015" alt="image" src="https://github.com/user-attachments/assets/dc835975-f766-4cbe-a47f-04e17fbdf5a8">

n=5
<img width="1082" alt="image" src="https://github.com/user-attachments/assets/4ccd8561-303f-4b20-9f6e-5b181992fe1e">

**Comment by william-silversmith** [comment]
This is released in version 11.0.0.

**Comment by RomStriker** [comment]
VMTK:
![image](https://github.com/user-attachments/assets/437e02b1-3e8d-45ba-a30f-1b479ad95cd7)

Kimimaro:
![image](https://github.com/user-attachments/assets/8815b10a-dc05-4179-9b7d-d6bee5afeb50)

Kimimaro n=3 smoothing:
![image](https://github.com/user-attachments/assets/76f540b3-fa08-4f68-a715-8ba37bcff19d)

Kimimaro n=5 smoothing:
![image](https://github.com/user-attachments/assets/c5a802df-9296-461f-8b68-1632207f8258)

Custom smoothing:
1. Get all simple paths from the root point to all the leaf points.
2. Apply `scipy.ndimage.gaussian_filter1d(path_pos, sigma=1, axis=0, mode="nearest")` on all the paths and update the positions.
![image](https://github.com/user-attachments/assets/ac8e9f96-44d8-4cb6-9ca8-31c286307d15)

I like the result of n=3 and the custom smoothing. n=5 introduces long edges, which results in non-equidistant nodes.

**Comment by william-silversmith** [comment]
That last one looks pretty good. I'll keep that in mind thanks!
